// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  TARGET_URL: string;
  STATUS_KV: KVNamespace;
  SLACK_WEBHOOK_URL?: string;
  TIMEOUT_MS?: number;
  RESET_HOURS_IN_UTC?: number;
}
